### ISSUE TITLE
some bugs, i think it's related to running on mac

### ISSUE THREAD

**Issue by chiptus** [figment-networks/tezos-batch-payments#1]
Hey, trying to use this script, beside baking I'm really missing an option to send batch payments and hopefully i'll be able to use your script.

Thanks for doing an awesome job

I have some bugs, after a lot of debugging I think it's because I'm running on mac

- there's a `log` command installed so it causes problem when you call `log`
- I think `sed` is working differently on mac, and when calling `extractRpcResponseField` it extracts the whole line and not only the required parameter
- $REVEAL is not defined, thus `jq` fails somewhere on the beginning

**Comment by rfunduk** [comment]
Hey thanks for the reports.

- The `REVEAL` var is old and should have been removed with the other references.
- `sed` should be `gnu-sed`, I added that to the readme that it is required on Mac.

Those are done in 99894e1c99f89dbbed1c06adef1e68cb1f24af50

For the `log` thing, it seems to work fine for me and just shadows the built-in command... Can you try this test script?

```
#!/usr/bin/env bash

function log() {
  echo "TEST -- $@"
}

log "this works fine?"
```

On my Mac I get the expected output from this.

**Comment by chiptus** [comment]
thanks for the fast response, I'm checking it now. for the gnu-sed vs sed, maybe add a check if there's the word Hash inside of the address string and if so, exit and report to install gnu-sed?

**Comment by chiptus** [comment]
another issue: total string shows jibrish instead of a number
![screenshot from 2019-01-05 20-46-13](https://user-images.githubusercontent.com/1381655/50727927-0a903680-112b-11e9-961f-553e335bde35.png)

**Comment by chiptus** [comment]
this was a mix of two bugs. 
1. for some reason when the tz symbol is attached to the number it prints it like that, when adding a space it fixes the jibrish.
2. $TOTAL_STRING is empty on line 199

**Comment by rfunduk** [comment]
I guess your terminal/font doesn't have the 'tz' character. I've been thinking to just change it to `XTZ` anyway so I'll do that.

For `$TOTAL_STRING`, please provide your command line. It's calculated starting here https://github.com/figment-networks/tezos-batch-payments/blob/master/tezos-batch-payments.bash#L531

**Comment by chiptus** [comment]
actually when I add space it shows the tz character correctly.
$TOTAL_STRING is calculated on line 531, but it's referenced on line 199 when doing --check-only, which is inside `setup` which is called before `main` where TOTAL_STRING is calculated.

**Comment by rfunduk** [comment]
So something about your terminal requires the space, but anyway I changed it to XTZ to avoid this problem.

I see, the problem is only when doing the check!
