### ISSUE TITLE
--transactions-file  Operation parsing error in prevalidation.

### ISSUE THREAD

**Issue by f3x** [figment-networks/tezos-batch-payments#11]
command line args: 
--transactions-file ./trans --use myalias --skip-funding --debug

  Injecting operation... OK Command failed : Operation parsing error in prevalidation.
  Waiting for confirmation... Error:
  Unrecognized command.
  Did you mean one of the following?
    wait for <operation> to be included [--confirmations <num_blocks>]
        [--check-previous <num_blocks>] [--branch <block_hash>]

Usage:
  tezos-client [global options] command [command options]
  tezos-client --help (for global options)
  tezos-client [global options] command --help (for command options)

**Comment by rfunduk** [comment]
Hey yea someone else had this same problem too but I can't reproduce it. I guess `Command failed : Operation parsing error in prevalidation.` is coming from the injection which has perhaps incorrect returned a status of 0 when really the injection failed. So then the injection response is not an op hash but that string about the command failing.

What's the rest of the output?

**Comment by rfunduk** [comment]
Shouldn't really be anything sensitive in the JSON? Anyway I'm not sure what to suggest if I can't see the rest of the log, like the simulate step and all that.
