### ISSUE TITLE
Rpc request failed

### ISSUE THREAD

**Issue by Xa52c** [figment-networks/tezos-batch-payments#12]
Sending transactions (page 1 of 1)...
  Forging operation... Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/forge/operations
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: No case matched:
  At /kind, unexpected string instead of endorsement
  At /kind, unexpected string instead of seed_nonce_revelation
  At /kind, unexpected string instead of double_endorsement_evidence
  At /kind, unexpected string instead of double_baking_evidence
  At /kind, unexpected string instead of activate_account
  At /kind, unexpected string instead of proposals
  At /kind, unexpected string instead of ballot
  At /kind, unexpected string instead of reveal
  Unhandled error (Invalid_argument "Z.of_substring_base: invalid digit")
  At /kind, unexpected string instead of origination
  At /kind, unexpected string instead of delegation
OK
  Signing operation... Enter password for encrypted key:

**Comment by rfunduk** [comment]
Hello there! Please provide the entire command line as well as the whole output (use code blocks when formatting) with the `--debug` flag.

**Comment by Xa52c** [comment]
`bash <( curl -sL https://git.io/fxMmp ) --use hotwallet --skip-funding --transactions-file cycle159b --debug |& tee output.txt
`
****************************************************************
***             Tezos Batch Payout Script                    ***
***                by Figment Networks                       ***
***              https://figment.network                     ***
*** https://github.com/figment-networks/tezos-batch-payments ***
****************************************************************

*** Warning: Not running in screen or tmux session!

*** Waiting 5...
*** Waiting 4...
*** Waiting 3...
*** Waiting 2...
*** Waiting 1...
*** Running anyway...

Checking node access... OK
Using account 'hotwallet'

Skipping funding (tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN requires 0.025092719 XTZ)...

Simulating... DEBUG -- Current head: "BMbhXQcwD6ZBKJHzVhMzFauzpJaTZRykDh43uqjcUJQLPqVuGcj"
DEBUG -- Current counter: 2264689
DEBUG -- Chain ID: "NetXdQprcVkpaWU"
DEBUG -- Transactions with counter: [{"kind":"transaction","amount":"1.00549665794945","destination":"KT1G6fh4PbKrLt1X8xLLJZQXH57vWBzqNE2g","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264690"},{"kind":"transaction","amount":"0.647257155078726","destination":"KT1NmrHzw48KEqS9wvPGoYWyMw6xMkRPowTk","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264691"},{"kind":"transaction","amount":"0.584878809566323","destination":"KT1EVY2mEDcj99bjnVqBscGhzyFD2FhncwUz","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264692"},{"kind":"transaction","amount":"0.541811543885974","destination":"KT1VGUmjGaLaEYbadvmiseeXveUm4rmjXTjw","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264693"},{"kind":"transaction","amount":"0.536445670010288","destination":"KT1C4mf96NHNvNwEBZn1HSweff4ArJF2EqKE","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264694"},{"kind":"transaction","amount":"0.368311176232675","destination":"KT196NroYzePuM44Q9X1jDqLV5jw8k7nbRPs","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264695"},{"kind":"transaction","amount":"0.267755711269539","destination":"KT1G3wvuh6hgWJVRk3qDXEYo2hJHchUcdBR8","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264696"},{"kind":"transaction","amount":"0.180061208763003","destination":"KT18pQLoPos6RaBCLmY68J4vW5go3ACUk5Qr","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264697"},{"kind":"transaction","amount":"0.138361384527484","destination":"KT1V3pGN3LBMKPZ9ijKp4LHfYyFDX8Hf18QJ","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264698"},{"kind":"transaction","amount":"0.134531788781538","destination":"KT1M9EN3rQ2iJpK9bYQA3Xs4pkbS7p4XAWKn","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264699"},{"kind":"transaction","amount":"0.13400750051348","destination":"KT1BTJbmsut7ACrHqp6z9ps3EpE68ztWfQog","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264700"},{"kind":"transaction","amount":"0.0669460944785332","destination":"KT1HZuyoG2hz2wcw2BPvbzaNCF1w237t16td","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264701"},{"kind":"transaction","amount":"0.0584865823614957","destination":"KT1HtYHUMBpoxTxprHJNVz3UBtnDZzgEhFTo","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264702"},{"kind":"transaction","amount":"0.0541953261444318","destination":"KT1FTVDBbucm1QfK2zFASznCFNxEz4bQbapv","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264703"}]
DEBUG -- Simulation run JSON: {"operation":{"branch":"BMbhXQcwD6ZBKJHzVhMzFauzpJaTZRykDh43uqjcUJQLPqVuGcj","contents":[{"kind":"transaction","amount":"1.00549665794945","destination":"KT1G6fh4PbKrLt1X8xLLJZQXH57vWBzqNE2g","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264690"},{"kind":"transaction","amount":"0.647257155078726","destination":"KT1NmrHzw48KEqS9wvPGoYWyMw6xMkRPowTk","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264691"},{"kind":"transaction","amount":"0.584878809566323","destination":"KT1EVY2mEDcj99bjnVqBscGhzyFD2FhncwUz","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264692"},{"kind":"transaction","amount":"0.541811543885974","destination":"KT1VGUmjGaLaEYbadvmiseeXveUm4rmjXTjw","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264693"},{"kind":"transaction","amount":"0.536445670010288","destination":"KT1C4mf96NHNvNwEBZn1HSweff4ArJF2EqKE","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264694"},{"kind":"transaction","amount":"0.368311176232675","destination":"KT196NroYzePuM44Q9X1jDqLV5jw8k7nbRPs","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264695"},{"kind":"transaction","amount":"0.267755711269539","destination":"KT1G3wvuh6hgWJVRk3qDXEYo2hJHchUcdBR8","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264696"},{"kind":"transaction","amount":"0.180061208763003","destination":"KT18pQLoPos6RaBCLmY68J4vW5go3ACUk5Qr","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264697"},{"kind":"transaction","amount":"0.138361384527484","destination":"KT1V3pGN3LBMKPZ9ijKp4LHfYyFDX8Hf18QJ","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264698"},{"kind":"transaction","amount":"0.134531788781538","destination":"KT1M9EN3rQ2iJpK9bYQA3Xs4pkbS7p4XAWKn","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264699"},{"kind":"transaction","amount":"0.13400750051348","destination":"KT1BTJbmsut7ACrHqp6z9ps3EpE68ztWfQog","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264700"},{"kind":"transaction","amount":"0.0669460944785332","destination":"KT1HZuyoG2hz2wcw2BPvbzaNCF1w237t16td","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264701"},{"kind":"transaction","amount":"0.0584865823614957","destination":"KT1HtYHUMBpoxTxprHJNVz3UBtnDZzgEhFTo","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264702"},{"kind":"transaction","amount":"0.0541953261444318","destination":"KT1FTVDBbucm1QfK2zFASznCFNxEz4bQbapv","storage_limit":"0","gas_limit":"15385","fee":"1792","source":"tz1fRAiiDUxnXZwDmQghh1n6VytQUZWNPwWN","counter":"2264703"}],"signature":"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"},"chain_id":"NetXdQprcVkpaWU"}
Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/scripts/run_operation
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: No case matched:
  At /kind, unexpected string instead of endorsement
  At /kind, unexpected string instead of seed_nonce_revelation
  At /kind, unexpected string instead of double_endorsement_evidence
  At /kind, unexpected string instead of double_baking_evidence
  At /kind, unexpected string instead of activate_account
  At /kind, unexpected string instead of proposals
  At /kind, unexpected string instead of ballot
  At /kind, unexpected string instead of reveal
  Unhandled error (Invalid_argument "Z.of_substring_base: invalid digit")
  At /kind, unexpected string instead of origination
  At /kind, unexpected string instead of delegation
DEBUG -- Results from simulation run: 
OK

Sending transactions (page 1 of 1)...
DEBUG -- Current counter: 2264689
  Forging operation... Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/forge/operations
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: No case matched:
  At /kind, unexpected string instead of endorsement
  At /kind, unexpected string instead of seed_nonce_revelation
  At /kind, unexpected string instead of double_endorsement_evidence
  At /kind, unexpected string instead of double_baking_evidence
  At /kind, unexpected string instead of activate_account
  At /kind, unexpected string instead of proposals
  At /kind, unexpected string instead of ballot
  At /kind, unexpected string instead of reveal
  Unhandled error (Invalid_argument "Z.of_substring_base: invalid digit")
  At /kind, unexpected string instead of origination
  At /kind, unexpected string instead of delegation
OK
  Signing operation... Enter password for encrypted key: Signature: edsigtb1ShgvDwDiTJdYLE9ztmz5D2MxMLkVZ1Ng6A59LJdMZECvu4R4BYurLsW5hbkcY9oZKqSdTnpti4uaBz59aaYPzo82QzN
OK
DEBUG -- Signature: edsigtb1ShgvDwDiTJdYLE9ztmz5D2MxMLkVZ1Ng6A59LJdMZECvu4R4BYurLsW5hbkcY9oZKqSdTnpti4uaBz59aaYPzo82QzN
  Preapply/check operation... Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/preapply/operations
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: No case matched:
  At /kind, unexpected string instead of endorsement
  At /kind, unexpected string instead of seed_nonce_revelation
  At /kind, unexpected string instead of double_endorsement_evidence
  At /kind, unexpected string instead of double_baking_evidence
  At /kind, unexpected string instead of activate_account
  At /kind, unexpected string instead of proposals
  At /kind, unexpected string instead of ballot
  At /kind, unexpected string instead of reveal
  Unhandled error (Invalid_argument "Z.of_substring_base: invalid digit")
  At /kind, unexpected string instead of origination
  At /kind, unexpected string instead of delegation
OK
DEBUG -- Preapply response: 
  Injecting operation... OK Command failed : Unknown branch (BKu4PsDeizCM), cannot inject the operation.
  Waiting for confirmation... bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `tezos-client wait for Command failed : Unknown branch (BKu4PsDeizCM), cannot inject the operation. to be included --confirmations 1 > /dev/null'
ERROR

Confirmation failed!
INFO: Check operation hash on tzscan or similar.

**Comment by rfunduk** [comment]
Weird, the 'Oups' message about forging an invalid request is from tezos-client, not this script. The JSON looks fine so I'm not sure what could be the problem. The only thing I can think of is that the amounts look a little odd, does your input file list the amounts in uxtz? There should be no decimal in them. How many entries do you have? I suppose it's possible the JSON is too long or something...

**Comment by Xa52c** [comment]
> does your input file list the amounts in uxtz? There should be no decimal in them.

this was the problem, listing the amounts in utz with no decimal solved it. thanks
