### ISSUE TITLE
could not inject operation

### ISSUE THREAD

**Issue by chiptus** [figment-networks/tezos-batch-payments#2]
for some reason injecting operation fails, with `unexpected server error`.

What can be the cause?

**Comment by chiptus** [comment]
tezos-client returns a vague error. when I'm doing the same operation with `curl` I get:
`[{"kind":"generic","error":"Operation onmdUi3n7vzbXqtJaLyKHuiSpsutdWxy9U2DSkerMafv6ANh8TS rejected by the mempool pre filter"}]`

i understand that it's because the fee is too low

**Comment by chiptus** [comment]
changing the fee to 0.00142 worked. I understand the fees need to be calculated per transaction, but not sure what is the algorithm

**Comment by chiptus** [comment]
https://www.reddit.com/r/tezos/comments/a17o7x/tezbox_now_charges_a_mining_fee/eanem7c/
0.00142 should be good

**Comment by rfunduk** [comment]
The script now adds a fee to every single transaction of 1110 uXTZ (0.00111 XTZ). This has been enough in every case and we've been using this in production for our bakery since cycle 33.

I do wonder though if it's something to do with cleaning out the float account. Try having some (any amount) funds in the float so that it isn't swept by the script when it sends.

**Comment by chiptus** [comment]
1110 < 1420, and if you see my attached link, this is the minimum fee. My float account has enough funding, and when I'm raising the hard coded fee it works.
Maybe it can be another flag in the script? --transaction-fee?

**Comment by rfunduk** [comment]
😄 I realize 1110 is less than 1420. The link you posted is about what _TezBox_ set to the low fee in their interface. I assure you 1110 uxtz is enough. Here is an operation from a few days ago where we paid our delegators at Figment using this script -- https://tzscan.io/op1soVY792QqPTR4mK39hrwAEc9Yr4omDkK1bmxCgJ5o1Cka4zY

I will add it to my todo list to make the fee configurable anyway when I get a chance.
