### ISSUE TITLE
Compatibility with Babylon update

### ISSUE THREAD

**Issue by FreedomPrevails** [figment-networks/tezos-batch-payments#7]
Hi,
Will the script be compatible with Babylon proposal ? I know it breaks wallets and they need to update their code:
https://blog.nomadic-labs.com/babylon-update-instructions-for-delegation-wallet-developers.html
 but I am not sure if it breaks this script or not ?

**Comment by rfunduk** [comment]
A good question! This project is not a wallet and shouldn't really be affected by the changes to how KT1s work as far as I know. It's simply batching payments together, whether they are to KT1s or tz1s is up to the software you use to generate the data fed to this script.

That said, I'm not sure. If you rely on this script and want to help out, you could test it on an appropriate testnet (zeronet, I guess? or a local sandbox network running the updated code) and let us know!
