### ISSUE TITLE
error after babylon update

### ISSUE THREAD

**Issue by FreedomPrevails** [figment-networks/tezos-batch-payments#8]
I am getting this error after babylon update :
```
Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/scripts/run_operation
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: Missing object field operation
Simulating... ERROR

Transaction simulation failed. Cannot continue!
```
I would appreciate if you can look into it ASAP. we use this script to process payments to our delegators.

**Comment by rfunduk** [comment]
Yea I think I saw something about this where this endpoint requires different json structure/nesting. I'm looking into it. A few other fires to put out first 😅

**Comment by FreedomPrevails** [comment]
Yeah, totally understood, we are all putting out fires after babylon upgrade 😅

**Comment by STFinancial** [comment]
I'm also using this script so a fix would be very helpful :)

**Comment by rfunduk** [comment]
I have the fix but so far unable to test due to TezBox and Tezos.id being behind by like 300 blocks it seems. Will keep you posted.

**Comment by STFinancial** [comment]
Alright, good luck. And thanks for your hard work. I've been using tzstats as a block explorer since the fork and it's been pretty good so far

**Comment by FreedomPrevails** [comment]
@rfunduk You can use https://tzstats.com. it is up to date.

**Comment by rfunduk** [comment]
Sadly my intended fix is not working. There's no error or anything it just fails simulation via `tezos-client`, and posting it via `curl` just gives garbage data back. At a bit of a loss here so if anyone else has any thoughts and wants to take a crack at it that'd be very helpful!

As far as I understand the json structure for `run_operation` (simulate step) changed. Instead of:

```
{ "branch": "...",  "contents": [...], "signature": "..." }
```

It's now:
```
{ "operation": { "branch": "...",  "contents": [...], "signature": "..." }, "chain_id": "..." }
```

This is an easy change which I have done, but it fails regardless 😓

**Comment by FreedomPrevails** [comment]
can you please share your fix ? I will try to look into it and work from there.

**Comment by jdsika** [comment]
You can have a look at [TRD](https://github.com/habanoz/tezos-reward-distributor) - The only thing failing right now is the transaction due to (I guess) wrong fees etc

**Comment by FreedomPrevails** [comment]
I think I found out the issue, It is related to gas limit, I am getting this error after fixing the script :
"errors": [ { "kind": "temporary", "id": "proto.005-PsBabyM1.gas_exhausted.operation" } ]
TRD has the same issue right now : https://github.com/habanoz/tezos-reward-distributor/issues/112

**Comment by jdsika** [comment]
damn gas prices are tooo damn highh *wrabbel wrabbel*

**Comment by rfunduk** [comment]
How did you get that error? My only change was querying for chain id:

```
# near the top
local chain_id=$($CLIENT_CMD rpc get /chains/main/chain_id)
# in args to assignment of run_json
    --argjson chain_id $chain_id \
```

Then adding that and the extra nesting:

```
    '. + {
      operation: {
        branch: $head,
        contents: $transactions,
        signature: $signature
      },
      chain_id: $chain_id
    }'
```

In the `simulateTransaction` function -- https://github.com/figment-networks/tezos-batch-payments/blob/master/tezos-batch-payments.bash#L370

**Comment by FreedomPrevails** [comment]
I have fixed the script and successfully injected an operation for test.
https://tzstats.com/operation/opQnU7NvwW6euvVri1zVaJUFtc5yubt5ajCj7Ct5fERH36urPnP
I am working on the final version. will post it when it is finished.

**Comment by FreedomPrevails** [comment]
Another test :
https://tzstats.com/operation/ooSbbpreGpPw6pyBtWUu1xDmQnoHM9A2BcYZseNXuRoELN4Nddv
looking good !

**Comment by FreedomPrevails** [comment]
pull request created.

**Comment by rfunduk** [comment]
Ok I think fixed (worked for our reward txs) in https://github.com/figment-networks/tezos-batch-payments/commit/2844f72506da52967fe48524611e94efda83312f

Thanks @FreedomPrevails for helping out with this!

**Comment by FreedomPrevails** [comment]
Glad to help :)
